{
  "data": {
    "codeFromReward": 0,
    "payeeIdentity": "",
    "payeeName": "",
    "vipValid": true,
    "wechatName": "染指",
    "qqToken": "",
    "deviceType": 2,
    "headImg": "https:\/\/thirdwx.qlogo.cn\/mmopen\/vi_32\/DYAIOgq83epNVjeMoibVTGSicdQFibSKlQObuicjBqvbquRohicdocLerLl86840MN8XSVndVqUFF6kMWFRvtEEWzHrqCUhsTQnSxicqtNZJo6m47XOnqET8YibxA\/132",
    "vipTime": 1,
    "appleUserId": "",
    "vipExpired": true,
    " name": "染指",
    "vipType": 3,
    "moneyAmount": 1,
    "id": 38164,
    "registerTime": 31,536,000,000,
    "token": "0s1URubpQ4Y5E88TqLkGsw==",
    "email": "",
    "kuanMailStatus": 0,
    "mobile": "",
    "wechatToken": "oaBG45omu2vn5V2xaIRCkMXnI5TM",
    "showInviteCode": 0,
    "qqName": "",
    "level": 1,
    "payByCodeTime": 0,
    "subLevel": 0,
    "blockInviteCode": 0,
    "subLevelSign": 0,
    "codeFrom": 0,
    "deviceCount": 1,
    "eduStatus": 0,
    "subLevelInvite": 0
  }
}